-- GHOSTRECON + WorkFlowVPS: schema Postgres puro para VPS (modelo "VPS = banco").
-- Aplique no database que recebera os writes do GhostRecon via DATABASE_URL e
-- que este workflow le via source_postgres (GHOSTRECON_SOURCE_DATABASE_URL).
--
--   psql "postgresql://USER:SENHA@127.0.0.1:5432/ghostworkflow" -f sql/ghostrecon_schema.sql

CREATE TABLE IF NOT EXISTS public.runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target TEXT NOT NULL,
  exact_match BOOLEAN NOT NULL DEFAULT FALSE,
  modules_json JSONB NOT NULL,
  stats_json JSONB NOT NULL,
  correlation_json JSONB,
  findings_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.findings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES public.runs (id) ON DELETE CASCADE,
  type TEXT,
  prio TEXT,
  score INTEGER,
  value TEXT,
  meta TEXT,
  url TEXT
);

CREATE INDEX IF NOT EXISTS findings_run_id_idx ON public.findings (run_id);
CREATE INDEX IF NOT EXISTS findings_type_idx ON public.findings (type);

CREATE TABLE IF NOT EXISTS public.bounty_intel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target TEXT NOT NULL,
  fp TEXT NOT NULL,
  type TEXT,
  prio TEXT,
  score INTEGER,
  value TEXT,
  meta TEXT,
  url TEXT,
  first_seen TIMESTAMPTZ NOT NULL,
  last_seen TIMESTAMPTZ NOT NULL,
  last_run_id BIGINT REFERENCES public.runs (id),
  UNIQUE (target, fp)
);

CREATE INDEX IF NOT EXISTS bounty_intel_target_idx ON public.bounty_intel (target);
CREATE INDEX IF NOT EXISTS bounty_intel_last_seen_idx ON public.bounty_intel (last_seen DESC);
CREATE INDEX IF NOT EXISTS bounty_intel_last_run_id_idx ON public.bounty_intel (last_run_id);
