import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = path.resolve(__dirname, '..', '..');

function slug(value, fallback = 'item') {
  const s = String(value || '')
    .toLowerCase()
    .replace(/https?:\/\//g, '')
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
  return s || fallback;
}

function timestamp(d = new Date()) {
  return d.toISOString().replace(/[:.]/g, '-');
}

function yamlString(value) {
  return JSON.stringify(String(value ?? ''));
}

function mdList(list) {
  const arr = Array.isArray(list) ? list : [];
  return arr.length ? arr.map((x) => `- ${String(x)}`).join('\n') : '- none';
}

function codeJson(value) {
  return `\`\`\`json\n${JSON.stringify(value ?? null, null, 2)}\n\`\`\``;
}

export function resolveAutoRagDir({ root = DEFAULT_ROOT, env = process.env } = {}) {
  const raw = String(env.GHOSTRECON_AUTO_RAG_DIR || '').trim();
  return raw ? path.resolve(raw) : path.join(root, 'data', 'auto-rag');
}

export async function ensureAutoRagDirs(opts = {}) {
  const base = resolveAutoRagDir(opts);
  const decisions = path.join(base, 'decisions');
  await fs.mkdir(decisions, { recursive: true });
  return { base, decisions };
}

export async function writeAutoDecisionMarkdown({
  root = DEFAULT_ROOT,
  env = process.env,
  requestRunId = '',
  target = '',
  kind = 'decision',
  title = '',
  summary = '',
  plan = null,
  evaluation = null,
  providers = null,
  catalog = null,
  events = [],
  tags = [],
} = {}) {
  if (/^(0|false|no|off)$/i.test(String(env.GHOSTRECON_AUTO_RAG_ENABLED || '1').trim())) {
    return null;
  }
  const dirs = await ensureAutoRagDirs({ root, env });
  const now = new Date();
  const safeKind = slug(kind, 'decision');
  const safeTarget = slug(target, 'target');
  const safeRun = slug(requestRunId || timestamp(now), 'run');
  const filename = `${timestamp(now)}-${safeTarget}-${safeKind}-${safeRun}.md`;
  const filePath = path.join(dirs.decisions, filename);
  const eventStats = {
    total: events.length,
    findings: events.filter((e) => e?.type === 'finding').length,
    errors: events.filter((e) => e?.type === 'error').length,
    warnings: events.filter((e) => e?.type === 'log' && e.level === 'warn').length,
  };
  const frontmatter = [
    '---',
    `type: ${yamlString('ghostrecon-auto-decision')}`,
    `kind: ${yamlString(kind)}`,
    `target: ${yamlString(target)}`,
    `requestRunId: ${yamlString(requestRunId)}`,
    `created: ${yamlString(now.toISOString())}`,
    `tags: [${['ghostrecon', 'auto-mode', ...tags].map((t) => yamlString(t)).join(', ')}]`,
    '---',
  ].join('\n');

  const body = [
    frontmatter,
    '',
    `# ${title || `GHOSTRECON Auto ${kind}`}`,
    '',
    '## Summary',
    '',
    summary || 'Decision generated by GHOSTRECON Auto Mode.',
    '',
    '## Target',
    '',
    `- Target: \`${target || 'unknown'}\``,
    `- Request run: \`${requestRunId || 'unknown'}\``,
    `- Kind: \`${kind}\``,
    '',
    '## Commander Roles',
    '',
    plan?.commanders?.roles
      ? mdList(Object.entries(plan.commanders.roles).map(([k, v]) => `${k}: ${v}`))
      : '- none',
    '',
    '## Selected Modules',
    '',
    mdList(plan?.modules || []),
    '',
    '## Event Stats',
    '',
    mdList(Object.entries(eventStats).map(([k, v]) => `${k}: ${v}`)),
    '',
    '## Evaluation',
    '',
    evaluation ? codeJson(evaluation) : '_Not available yet._',
    '',
    '## Plan',
    '',
    plan ? codeJson(plan) : '_Not available._',
    '',
    '## Providers',
    '',
    providers ? codeJson(providers) : '_Not available._',
    '',
    '## Catalog Snapshot',
    '',
    catalog ? codeJson(catalog) : '_Not available._',
    '',
  ].join('\n');

  await fs.writeFile(filePath, body, 'utf8');
  await updateAutoRagIndex({ root, env });
  return { filePath, filename, baseDir: dirs.base };
}

export async function listAutoRagMarkdown({ root = DEFAULT_ROOT, env = process.env, limit = 20 } = {}) {
  const dirs = await ensureAutoRagDirs({ root, env });
  const entries = await fs.readdir(dirs.decisions, { withFileTypes: true }).catch(() => []);
  const files = entries
    .filter((e) => e.isFile() && e.name.toLowerCase().endsWith('.md'))
    .map((e) => e.name)
    .sort()
    .reverse()
    .slice(0, Math.max(1, Math.min(200, Number(limit) || 20)));
  return Promise.all(files.map(async (name) => {
    const filePath = path.join(dirs.decisions, name);
    const text = await fs.readFile(filePath, 'utf8').catch(() => '');
    const firstHeading = /^#\s+(.+)$/m.exec(text)?.[1] || name;
    return {
      name,
      path: filePath,
      title: firstHeading,
      preview: text.replace(/^---[\s\S]*?---\s*/m, '').trim().slice(0, 900),
    };
  }));
}

export async function readAutoRagMarkdown(name, { root = DEFAULT_ROOT, env = process.env } = {}) {
  const dirs = await ensureAutoRagDirs({ root, env });
  const safe = path.basename(String(name || ''));
  if (!safe || !safe.endsWith('.md')) throw new Error('nome de memoria invalido');
  const filePath = path.join(dirs.decisions, safe);
  return { name: safe, path: filePath, text: await fs.readFile(filePath, 'utf8') };
}

export async function loadAutoRagContext({ root = DEFAULT_ROOT, env = process.env, limit = 6 } = {}) {
  const items = await listAutoRagMarkdown({ root, env, limit });
  return {
    dir: resolveAutoRagDir({ root, env }),
    items: items.map((item) => ({
      name: item.name,
      title: item.title,
      preview: item.preview,
    })),
  };
}

export async function updateAutoRagIndex({ root = DEFAULT_ROOT, env = process.env } = {}) {
  const dirs = await ensureAutoRagDirs({ root, env });
  const items = await listAutoRagMarkdown({ root, env, limit: 200 });
  const indexPath = path.join(dirs.base, 'README.md');
  const text = [
    '# GHOSTRECON Auto RAG',
    '',
    'Markdown memory generated by GHOSTRECON Auto Mode. Open this folder as an Obsidian vault or add it to an existing vault.',
    '',
    '## Decisions',
    '',
    ...items.map((item) => `- [[decisions/${item.name.replace(/\.md$/i, '')}]] - ${item.title}`),
    '',
  ].join('\n');
  await fs.writeFile(indexPath, text, 'utf8');
  return { indexPath, count: items.length };
}

