import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = path.resolve(__dirname, '..', '..');

function slug(value, fallback = 'item') {
  const s = String(value || '')
    .toLowerCase()
    .replace(/https?:\/\//g, '')
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
  return s || fallback;
}

function timestamp(d = new Date()) {
  return d.toISOString().replace(/[:.]/g, '-');
}

function yamlString(value) {
  return JSON.stringify(String(value ?? ''));
}

function mdList(list) {
  const arr = Array.isArray(list) ? list : [];
  return arr.length ? arr.map((x) => `- ${String(x)}`).join('\n') : '- none';
}

function codeJson(value) {
  return `\`\`\`json\n${JSON.stringify(value ?? null, null, 2)}\n\`\`\``;
}

const MEMORY_FOLDERS = Object.freeze({
  decisions: 'decisions',
  lessons: 'lessons',
  notes: 'notes',
  cursorTasks: 'cursor-tasks',
});

function clampLimit(value, fallback = 20, max = 200) {
  return Math.max(1, Math.min(max, Number(value) || fallback));
}

function normalizeTags(tags) {
  return [...new Set(['ghostrecon', 'auto-mode', ...(Array.isArray(tags) ? tags : [])]
    .map((t) => String(t || '').trim())
    .filter(Boolean))];
}

function stripFrontmatter(text) {
  return String(text || '').replace(/^---[\s\S]*?---\s*/m, '').trim();
}

function folderForKind(kind = '') {
  const k = String(kind || '').trim().toLowerCase();
  if (['lesson', 'lessons'].includes(k)) return MEMORY_FOLDERS.lessons;
  if (['note', 'notes'].includes(k)) return MEMORY_FOLDERS.notes;
  if (['cursor', 'cursor-task', 'cursor_tasks', 'cursor-tasks'].includes(k)) return MEMORY_FOLDERS.cursorTasks;
  return MEMORY_FOLDERS.decisions;
}

function safeMemoryRef(name) {
  const raw = String(name || '').trim().replace(/\\/g, '/');
  const parts = raw.split('/').filter(Boolean);
  const file = path.basename(parts.pop() || '');
  const folder = parts.length ? parts[parts.length - 1] : MEMORY_FOLDERS.decisions;
  if (!file || !file.toLowerCase().endsWith('.md')) throw new Error('nome de memoria invalido');
  const allowed = new Set(Object.values(MEMORY_FOLDERS));
  if (!allowed.has(folder)) throw new Error('pasta de memoria invalida');
  return { folder, file, ref: `${folder}/${file}` };
}

export function resolveAutoRagDir({ root = DEFAULT_ROOT, env = process.env } = {}) {
  const raw = String(env.GHOSTRECON_AUTO_RAG_DIR || '').trim();
  return raw ? path.resolve(raw) : path.join(root, 'data', 'auto-rag');
}

export async function ensureAutoRagDirs(opts = {}) {
  const base = resolveAutoRagDir(opts);
  const dirs = { base };
  for (const [key, folder] of Object.entries(MEMORY_FOLDERS)) {
    dirs[key] = path.join(base, folder);
    await fs.mkdir(dirs[key], { recursive: true });
  }
  return dirs;
}

export async function writeAutoDecisionMarkdown({
  root = DEFAULT_ROOT,
  env = process.env,
  requestRunId = '',
  target = '',
  kind = 'decision',
  title = '',
  summary = '',
  plan = null,
  evaluation = null,
  providers = null,
  catalog = null,
  events = [],
  tags = [],
} = {}) {
  if (/^(0|false|no|off)$/i.test(String(env.GHOSTRECON_AUTO_RAG_ENABLED || '1').trim())) {
    return null;
  }
  const dirs = await ensureAutoRagDirs({ root, env });
  const now = new Date();
  const safeKind = slug(kind, 'decision');
  const safeTarget = slug(target, 'target');
  const safeRun = slug(requestRunId || timestamp(now), 'run');
  const filename = `${timestamp(now)}-${safeTarget}-${safeKind}-${safeRun}.md`;
  const filePath = path.join(dirs.decisions, filename);
  const eventStats = {
    total: events.length,
    findings: events.filter((e) => e?.type === 'finding').length,
    errors: events.filter((e) => e?.type === 'error').length,
    warnings: events.filter((e) => e?.type === 'log' && e.level === 'warn').length,
  };
  const frontmatter = [
    '---',
    `type: ${yamlString('ghostrecon-auto-decision')}`,
    `kind: ${yamlString(kind)}`,
    `target: ${yamlString(target)}`,
    `requestRunId: ${yamlString(requestRunId)}`,
    `created: ${yamlString(now.toISOString())}`,
    `tags: [${normalizeTags(tags).map((t) => yamlString(t)).join(', ')}]`,
    '---',
  ].join('\n');

  const body = [
    frontmatter,
    '',
    `# ${title || `GHOSTRECON Auto ${kind}`}`,
    '',
    '## Summary',
    '',
    summary || 'Decision generated by GHOSTRECON Auto Mode.',
    '',
    '## Target',
    '',
    `- Target: \`${target || 'unknown'}\``,
    `- Request run: \`${requestRunId || 'unknown'}\``,
    `- Kind: \`${kind}\``,
    '',
    '## Commander Roles',
    '',
    plan?.commanders?.roles
      ? mdList(Object.entries(plan.commanders.roles).map(([k, v]) => `${k}: ${v}`))
      : '- none',
    '',
    '## Selected Modules',
    '',
    mdList(plan?.modules || []),
    '',
    '## Event Stats',
    '',
    mdList(Object.entries(eventStats).map(([k, v]) => `${k}: ${v}`)),
    '',
    '## Evaluation',
    '',
    evaluation ? codeJson(evaluation) : '_Not available yet._',
    '',
    '## Plan',
    '',
    plan ? codeJson(plan) : '_Not available._',
    '',
    '## Providers',
    '',
    providers ? codeJson(providers) : '_Not available._',
    '',
    '## Catalog Snapshot',
    '',
    catalog ? codeJson(catalog) : '_Not available._',
    '',
  ].join('\n');

  await fs.writeFile(filePath, body, 'utf8');
  await updateAutoRagIndex({ root, env });
  return { filePath, filename, baseDir: dirs.base };
}

export async function writeAutoRagNote({
  root = DEFAULT_ROOT,
  env = process.env,
  kind = 'note',
  title = '',
  body = '',
  target = '',
  tags = [],
  metadata = null,
} = {}) {
  if (/^(0|false|no|off)$/i.test(String(env.GHOSTRECON_AUTO_RAG_ENABLED || '1').trim())) {
    return null;
  }
  const dirs = await ensureAutoRagDirs({ root, env });
  const now = new Date();
  const folder = folderForKind(kind);
  const safeTitle = slug(title || kind, kind);
  const filename = `${timestamp(now)}-${safeTitle}.md`;
  const filePath = path.join(dirs[folder === MEMORY_FOLDERS.cursorTasks ? 'cursorTasks' : folder], filename);
  const frontmatter = [
    '---',
    `type: ${yamlString('ghostrecon-auto-memory')}`,
    `kind: ${yamlString(kind)}`,
    `target: ${yamlString(target)}`,
    `created: ${yamlString(now.toISOString())}`,
    `tags: [${normalizeTags([kind, ...tags]).map((t) => yamlString(t)).join(', ')}]`,
    '---',
  ].join('\n');
  const text = [
    frontmatter,
    '',
    `# ${title || `Auto ${kind}`}`,
    '',
    body || '_No body provided._',
    '',
    metadata ? '## Metadata' : '',
    metadata ? codeJson(metadata) : '',
  ].filter((line, idx, arr) => line !== '' || arr[idx - 1] !== '').join('\n');
  await fs.writeFile(filePath, text, 'utf8');
  await updateAutoRagIndex({ root, env });
  return { filePath, filename, name: `${folder}/${filename}`, kind, baseDir: dirs.base };
}

export async function writeAutoLesson({
  root = DEFAULT_ROOT,
  env = process.env,
  target = '',
  problem = '',
  decision = '',
  outcome = '',
  modules = [],
  commanders = null,
  confidence = '',
  tags = [],
  metadata = null,
} = {}) {
  const title = `Lesson - ${target || slug(problem, 'auto')}`;
  const body = [
    '## Problem',
    '',
    problem || '_Not provided._',
    '',
    '## Decision',
    '',
    decision || '_Not provided._',
    '',
    '## Outcome',
    '',
    outcome || '_Pending._',
    '',
    '## Modules',
    '',
    mdList(modules),
    '',
    '## Commanders',
    '',
    commanders ? codeJson(commanders) : '_Not provided._',
    '',
    '## Confidence',
    '',
    confidence || '_Not provided._',
  ].join('\n');
  return writeAutoRagNote({
    root,
    env,
    kind: 'lesson',
    title,
    body,
    target,
    tags: ['lesson', ...tags],
    metadata,
  });
}

export async function listAutoRagMarkdown({ root = DEFAULT_ROOT, env = process.env, limit = 20 } = {}) {
  const dirs = await ensureAutoRagDirs({ root, env });
  const files = [];
  for (const [key, folder] of Object.entries({
    decisions: dirs.decisions,
    lessons: dirs.lessons,
    notes: dirs.notes,
    'cursor-tasks': dirs.cursorTasks,
  })) {
    const entries = await fs.readdir(folder, { withFileTypes: true }).catch(() => []);
    for (const e of entries) {
      if (e.isFile() && e.name.toLowerCase().endsWith('.md')) {
        files.push({ folder: key, name: e.name, path: path.join(folder, e.name) });
      }
    }
  }
  const selected = files
    .sort((a, b) => b.name.localeCompare(a.name))
    .slice(0, clampLimit(limit, 20, 500));
  return Promise.all(selected.map(async (item) => {
    const text = await fs.readFile(item.path, 'utf8').catch(() => '');
    const firstHeading = /^#\s+(.+)$/m.exec(text)?.[1] || item.name;
    return {
      name: `${item.folder}/${item.name}`,
      file: item.name,
      folder: item.folder,
      path: item.path,
      title: firstHeading,
      preview: stripFrontmatter(text).slice(0, 900),
    };
  }));
}

export async function readAutoRagMarkdown(name, { root = DEFAULT_ROOT, env = process.env } = {}) {
  const dirs = await ensureAutoRagDirs({ root, env });
  const safe = safeMemoryRef(name);
  const dirKey = safe.folder === MEMORY_FOLDERS.cursorTasks ? 'cursorTasks' : safe.folder;
  const filePath = path.join(dirs[dirKey], safe.file);
  return { name: safe.ref, file: safe.file, folder: safe.folder, path: filePath, text: await fs.readFile(filePath, 'utf8') };
}

export async function searchAutoRagMarkdown({
  query = '',
  root = DEFAULT_ROOT,
  env = process.env,
  limit = 8,
  scanLimit = 120,
} = {}) {
  const q = String(query || '').trim().toLowerCase();
  const terms = q
    .split(/[^a-z0-9._-]+/i)
    .map((x) => x.trim().toLowerCase())
    .filter((x) => x.length >= 2);
  const items = await listAutoRagMarkdown({ root, env, limit: scanLimit });
  if (!terms.length) return items.slice(0, clampLimit(limit, 8, 50));

  const scored = [];
  for (const item of items) {
    const text = await fs.readFile(item.path, 'utf8').catch(() => '');
    const hay = `${item.name}\n${item.title}\n${text}`.toLowerCase();
    let score = 0;
    for (const term of terms) {
      const matches = hay.split(term).length - 1;
      score += matches * (item.title.toLowerCase().includes(term) ? 3 : 1);
    }
    if (score > 0) {
      scored.push({
        ...item,
        score,
        preview: stripFrontmatter(text).slice(0, 1400),
      });
    }
  }
  return scored
    .sort((a, b) => b.score - a.score || b.name.localeCompare(a.name))
    .slice(0, clampLimit(limit, 8, 50));
}

export async function loadAutoRagContext({ root = DEFAULT_ROOT, env = process.env, limit = 6 } = {}) {
  const items = await listAutoRagMarkdown({ root, env, limit });
  return {
    dir: resolveAutoRagDir({ root, env }),
    items: items.map((item) => ({
      name: item.name,
      folder: item.folder,
      title: item.title,
      preview: item.preview,
    })),
  };
}

export async function updateAutoRagIndex({ root = DEFAULT_ROOT, env = process.env } = {}) {
  const dirs = await ensureAutoRagDirs({ root, env });
  const items = await listAutoRagMarkdown({ root, env, limit: 200 });
  const indexPath = path.join(dirs.base, 'README.md');
  const byFolder = new Map();
  for (const item of items) {
    if (!byFolder.has(item.folder)) byFolder.set(item.folder, []);
    byFolder.get(item.folder).push(item);
  }
  const section = (folder, title) => [
    `## ${title}`,
    '',
    ...(byFolder.get(folder) || []).map((item) => `- [[${item.name.replace(/\.md$/i, '')}]] - ${item.title}`),
    '',
  ];
  const text = [
    '# GHOSTRECON Auto RAG',
    '',
    'Markdown memory generated by GHOSTRECON Auto Mode. Open this folder as an Obsidian vault or add it to an existing vault.',
    '',
    ...section('decisions', 'Decisions'),
    ...section('lessons', 'Lessons'),
    ...section('notes', 'Notes'),
    ...section('cursor-tasks', 'Cursor Tasks'),
  ].join('\n');
  await fs.writeFile(indexPath, text, 'utf8');
  return { indexPath, count: items.length };
}
