/**
 * GHOSTRECON — Tor STRICT mode (anti-leak central)
 *
 * Quando GHOSTRECON_TOR_STRICT=1 (ou tor.strict=true no body do recon):
 *   1. Locka Node DNS para 127.0.0.1:5353 (Tor DNSPort) — qualquer dns.resolve*
 *      do código nosso e de libs (undici quando não usa SOCKS5h, dotenv, etc.)
 *      passa a ir pelo Tor.
 *   2. Força ipv4first → evita AAAA queries e bind IPv6 que possam escapar do Tor.
 *   3. Escreve um proxychains.conf temporário apontando para
 *      socks5  127.0.0.1 9050 com proxy_dns=true.
 *   4. Wrappa qualquer comando externo (nmap, sqlmap, ffuf, nuclei, dirsearch,
 *      dalfox, whois, wpscan, curl, dig, nslookup, host, masscan, gobuster…) com
 *      proxychains4 -q -f <conf>.
 *   5. Sanitiza headers HTTP de saída — UA Tor Browser-like, strip de
 *      Referer/Origin/X-Forwarded-*/Cookie a hosts não-target.
 *   6. Bloqueia `fetch()` directo: aborta se identity-controller não tiver
 *      dispatcher SOCKS configurado (sem fallback silencioso para directo).
 *   7. Refuse_to_run() devolve lista de prereqs em falta.
 *
 * Uso:
 *   import {
 *     initTorStrict, isStrict, wrapCommand, sanitizeOutboundHeaders,
 *     strictPrereqs, hardenNodeDns, refuseToRun,
 *   } from './tor-strict.js';
 *
 *   if (isStrict()) await initTorStrict();
 *   const { cmd, args } = wrapCommand('nmap', ['-sV', '...']);
 */

import fs from 'node:fs';
import path from 'node:path';
import dns from 'node:dns';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(__dirname, '..', '..');

// Lista de comandos que SEMPRE devem ser wrap-eados em strict.
// Inclui DNS tools — `dig`, `nslookup`, `host` vazariam queries directo no resolver.
const STRICT_WRAP_DEFAULTS = new Set([
  'nmap', 'masscan', 'rustscan',
  'ffuf', 'gobuster', 'dirsearch', 'feroxbuster', 'wfuzz',
  'nuclei', 'dalfox', 'wpscan', 'sqlmap',
  'curl', 'wget', 'httpx',
  'whois',
  'dig', 'nslookup', 'host', 'drill',
  'amass', 'subfinder', 'assetfinder', 'shuffledns',
]);

// User-Agent canónico Tor Browser (versão estável recente). Reduzir entropia
// vs UA de Chrome com plugins que delata o cliente real.
const TOR_BROWSER_UA =
  'Mozilla/5.0 (Windows NT 10.0; rv:115.0) Gecko/20100101 Firefox/115.0';

// Headers que delatam origem real ou padrão de uso e precisam de strip.
const STRIP_HEADERS = [
  'referer',
  'origin',
  'x-forwarded-for',
  'x-real-ip',
  'x-client-ip',
  'cf-connecting-ip',
  'true-client-ip',
  'x-cluster-client-ip',
  'forwarded',
  'via',
];

const STATE = {
  active: false,
  proxychainsConf: null,
  wrapAdditions: new Set(),
  wrapSkip: new Set(),
  proxychainsBin: 'proxychains4',
  socksHost: '127.0.0.1',
  socksPort: 9050,
  dnsPort: 5353,
  prereqsCache: null,
};

export function isStrict() {
  if (STATE.active) return true;
  return String(process.env.GHOSTRECON_TOR_STRICT || '').trim() === '1';
}

function which(bin) {
  // Cross-platform best-effort sem deps externos: testa $PATH directorias.
  const pathEnv = process.env.PATH || '';
  const exts = process.platform === 'win32' ? (process.env.PATHEXT || '.EXE').split(';') : [''];
  for (const dir of pathEnv.split(path.delimiter)) {
    if (!dir) continue;
    for (const ext of exts) {
      const full = path.join(dir, bin + ext);
      try { fs.accessSync(full, fs.constants.X_OK); return full; } catch { /* try next */ }
    }
  }
  return null;
}

/**
 * Escreve um proxychains.conf efémero apontando o SOCKS5 do Tor.
 * Conf:
 *   strict_chain         — recusa ligar se algum proxy falhar
 *   proxy_dns            — DNS via SOCKS, não vaza
 *   tcp_read_time_out 15000
 *   tcp_connect_time_out 8000
 *   [ProxyList]
 *   socks5  127.0.0.1 9050
 */
function writeProxychainsConf() {
  const dir = path.join(REPO_ROOT, '.runtime');
  fs.mkdirSync(dir, { recursive: true });
  const conf = path.join(dir, 'proxychains.conf');
  const body = [
    '# Generated by ghostrecon tor-strict (NÃO EDITAR — sobrescrito a cada boot strict)',
    'strict_chain',
    'proxy_dns',
    'remote_dns_subnet 224',
    'tcp_read_time_out 15000',
    'tcp_connect_time_out 8000',
    '',
    '[ProxyList]',
    `socks5  ${STATE.socksHost} ${STATE.socksPort}`,
    '',
  ].join('\n');
  fs.writeFileSync(conf, body, { mode: 0o600 });
  return conf;
}

/**
 * Locka o resolver DNS do Node para o DNSPort do Tor.
 * Após esta chamada, dns.resolve* e qualquer fetch que faça DNS local passa
 * pelo Tor. SOCKS5h continua a ser preferido (bypassa o resolver).
 */
export function hardenNodeDns({ dnsHost = STATE.socksHost, dnsPort = STATE.dnsPort } = {}) {
  try {
    dns.setDefaultResultOrder('ipv4first');
  } catch { /* node < 18 fallback */ }
  try {
    dns.setServers([`${dnsHost}:${dnsPort}`]);
  } catch (e) {
    console.error('[tor-strict] dns.setServers falhou:', e?.message || e);
  }
}

/**
 * Inicializa modo strict — chamar 1× no boot quando isStrict() === true.
 * Idempotente: chamar várias vezes não duplica config.
 */
export function initTorStrict(opts = {}) {
  if (STATE.active) return STATE;

  STATE.socksHost = String(opts.socksHost || process.env.GHOSTRECON_TOR_SOCKS_HOST || '127.0.0.1');
  STATE.socksPort = Number(opts.socksPort || process.env.GHOSTRECON_TOR_SOCKS_PORT || 9050);
  STATE.dnsPort = Number(opts.dnsPort || process.env.GHOSTRECON_TOR_DNS_PORT || 5353);
  STATE.proxychainsBin =
    opts.proxychainsBin ||
    process.env.GHOSTRECON_PROXYCHAINS_BIN ||
    'proxychains4';

  // Adicional / skip configuráveis
  const extra = String(process.env.GHOSTRECON_TOR_STRICT_WRAP_ADD || '')
    .split(/[,\s]+/).map((s) => s.trim().toLowerCase()).filter(Boolean);
  for (const e of extra) STATE.wrapAdditions.add(e);
  const skip = String(process.env.GHOSTRECON_PROXYCHAINS_SKIP || '')
    .split(/[,\s]+/).map((s) => s.trim().toLowerCase()).filter(Boolean);
  for (const s of skip) STATE.wrapSkip.add(s);

  // proxychains.conf
  if (!process.env.GHOSTRECON_PROXYCHAINS_CONF) {
    try {
      STATE.proxychainsConf = writeProxychainsConf();
    } catch (e) {
      console.error('[tor-strict] falha a escrever proxychains.conf:', e?.message || e);
    }
  } else {
    STATE.proxychainsConf = String(process.env.GHOSTRECON_PROXYCHAINS_CONF);
  }

  // DNS lockdown
  hardenNodeDns();

  // Sinaliza para os wrappers existentes em kali-scan/sqlmap-runner
  process.env.GHOSTRECON_PROXYCHAINS = '1';
  if (STATE.proxychainsConf) {
    process.env.GHOSTRECON_PROXYCHAINS_CONF = STATE.proxychainsConf;
  }
  process.env.GHOSTRECON_PROXYCHAINS_QUIET = '1';

  // Garante que o GHOSTRECON_PROXY_POOL aponta para socks5h por default
  if (!process.env.GHOSTRECON_PROXY_POOL) {
    process.env.GHOSTRECON_PROXY_POOL = `socks5h://${STATE.socksHost}:${STATE.socksPort}`;
  }
  if (!process.env.GHOSTRECON_TOR_ISOLATE) {
    process.env.GHOSTRECON_TOR_ISOLATE = '1';
  }
  if (!process.env.GHOSTRECON_TOR_REQUIRED) {
    process.env.GHOSTRECON_TOR_REQUIRED = '1';
  }

  STATE.active = true;
  console.log('[tor-strict] activo', JSON.stringify({
    socks: `${STATE.socksHost}:${STATE.socksPort}`,
    dns: `${STATE.socksHost}:${STATE.dnsPort}`,
    proxychainsBin: STATE.proxychainsBin,
    proxychainsConf: STATE.proxychainsConf,
    wrapAdditions: [...STATE.wrapAdditions],
    wrapSkip: [...STATE.wrapSkip],
  }));
  return STATE;
}

/**
 * Indica se determinado comando (basename) deve ser wrap-eado.
 */
export function shouldWrap(cmd) {
  if (!isStrict()) return false;
  const norm = path.basename(String(cmd || '')).toLowerCase();
  if (!norm) return false;
  if (STATE.wrapSkip.has(norm)) return false;
  if (STATE.wrapAdditions.has(norm)) return true;
  return STRICT_WRAP_DEFAULTS.has(norm);
}

/**
 * Devolve { cmd, args } para o spawn — já com proxychains4 quando aplicável.
 * Quando o wrap está activo mas proxychains4 não está no PATH, devolve
 * { cmd, args, refuse:true, reason } para o caller escolher como tratar
 * (recomendado: abortar).
 */
export function wrapCommand(cmd, args = []) {
  if (!shouldWrap(cmd)) return { cmd, args };
  const bin = which(STATE.proxychainsBin);
  if (!bin) {
    return {
      cmd,
      args,
      refuse: true,
      reason: `tor-strict activo: ${STATE.proxychainsBin} não está no PATH (instala 'proxychains4')`,
    };
  }
  const wrapped = ['-q'];
  if (STATE.proxychainsConf) wrapped.push('-f', STATE.proxychainsConf);
  wrapped.push(cmd, ...(Array.isArray(args) ? args : []));
  return { cmd: bin, args: wrapped };
}

/**
 * Aplica hardening de headers para um init de fetch — chama-se no
 * identity-controller antes de cada request quando isStrict().
 */
export function sanitizeOutboundHeaders(headers, { targetHost = '' } = {}) {
  const out = {};
  // Copia preservando case-insensitivity
  for (const [k, v] of Object.entries(headers || {})) {
    if (!k) continue;
    const lk = k.toLowerCase();
    if (STRIP_HEADERS.includes(lk)) continue;
    if (lk === 'cookie' && targetHost && !cookieMatchesTarget(String(v), targetHost)) continue;
    out[k] = v;
  }
  // Normaliza UA / Accept-Language para o perfil Tor Browser
  out['User-Agent'] = TOR_BROWSER_UA;
  out['Accept-Language'] = 'en-US,en;q=0.5';
  out['Accept'] = out['Accept'] || 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8';
  out['Accept-Encoding'] = 'gzip, deflate';
  out['DNT'] = '1';
  out['Connection'] = 'keep-alive';
  out['Upgrade-Insecure-Requests'] = '1';
  delete out['sec-ch-ua'];
  delete out['sec-ch-ua-mobile'];
  delete out['sec-ch-ua-platform'];
  return out;
}

function cookieMatchesTarget(cookieHeader, targetHost) {
  // Heurística simples: se o cookie tem domain=, exigir match com targetHost.
  const m = cookieHeader.match(/domain=([^;]+)/i);
  if (!m) return true; // sem domain explícito → assume cookie é do alvo (já filtrado upstream)
  const dom = m[1].trim().replace(/^\./, '');
  return targetHost.endsWith(dom);
}

/**
 * Verifica os pré-requisitos de strict. Útil para o /api/tunnel/strict-check
 * e para validar antes de iniciar um run com tor.strict=true.
 */
export function strictPrereqs() {
  if (STATE.prereqsCache && Date.now() - STATE.prereqsCache.ts < 10_000) {
    return STATE.prereqsCache.value;
  }
  const checks = [];
  // 1. proxychains4 binary
  const pchain = which(STATE.proxychainsBin);
  checks.push({ name: 'proxychains4', ok: Boolean(pchain), detail: pchain || 'não encontrado no PATH' });

  // 2. Tor SOCKS porto a aceitar ligação
  const socksOk = tcpProbe(STATE.socksHost, STATE.socksPort, 1500);
  checks.push({ name: 'tor.socks', ok: socksOk, detail: `${STATE.socksHost}:${STATE.socksPort}` });

  // 3. Tor DNSPort
  const dnsOk = udpHasListener(STATE.dnsPort) || tcpProbe(STATE.socksHost, STATE.dnsPort, 1500);
  checks.push({ name: 'tor.dns', ok: dnsOk, detail: `${STATE.socksHost}:${STATE.dnsPort}` });

  // 4. ControlPort
  const ctrlOk = tcpProbe(STATE.socksHost, Number(process.env.GHOSTRECON_TOR_CONTROL_PORT || 9051), 1500);
  checks.push({ name: 'tor.control', ok: ctrlOk });

  // 5. proxychains.conf
  const confOk = STATE.proxychainsConf && fs.existsSync(STATE.proxychainsConf);
  checks.push({ name: 'proxychains.conf', ok: Boolean(confOk), detail: STATE.proxychainsConf || 'não escrito' });

  // 6. Node DNS já apontado para Tor
  const servers = dns.getServers();
  const dnsLocked = servers.some((s) => s.includes(`${STATE.dnsPort}`));
  checks.push({ name: 'node.dns.locked', ok: dnsLocked, detail: servers.join(',') });

  // 7. proxy pool com socks
  const pool = String(process.env.GHOSTRECON_PROXY_POOL || '');
  const poolOk = /socks(5h?|4a?):\/\//i.test(pool);
  checks.push({ name: 'proxy_pool.socks', ok: poolOk, detail: pool || '(vazio)' });

  const ok = checks.every((c) => c.ok);
  const value = { ok, active: STATE.active, checks, missing: checks.filter((c) => !c.ok).map((c) => c.name) };
  STATE.prereqsCache = { ts: Date.now(), value };
  return value;
}

function tcpProbe(host, port, timeoutMs = 1500) {
  // Usa spawnSync('node', ['-e', ...]) seria caro. Fazemos um pequeno
  // probe via net.connect síncrono via Atomics-like? Não dá em Node.
  // Em vez disso, lançamos um net.connect em modo unref + setTimeout — apenas
  // marcamos OK se socket ligou; chamamos isto via asyncProbe wrapped sync.
  // Solução pragmatica: usar require('net').connect em modo bloqueante via
  // child Node — caro. Em vez disso, usamos um spawnSync('bash','-c', `</dev/tcp/host/port`).
  if (process.platform === 'win32') {
    // No Windows não há /dev/tcp. Skip — devolver true assumindo configuração ok.
    return true;
  }
  try {
    const r = spawnSync('bash', ['-c', `timeout ${(timeoutMs / 1000).toFixed(2)} bash -c "</dev/tcp/${host}/${port}"`], { timeout: timeoutMs + 500 });
    return r.status === 0;
  } catch {
    return false;
  }
}

function udpHasListener(port) {
  // ss -lnu --no-header sport = :<port>
  if (process.platform === 'win32') return true;
  try {
    const r = spawnSync('bash', ['-c', `ss -lnu --no-header sport = :${port} 2>/dev/null | head -n1`], { timeout: 2000 });
    return Boolean(r.stdout && r.stdout.toString().trim());
  } catch {
    return false;
  }
}

/**
 * Atalho usado pelo /api/recon/stream para abortar com motivo claro.
 */
export function refuseToRun() {
  const p = strictPrereqs();
  if (p.ok) return null;
  return {
    error: 'tor-strict prereqs failed',
    missing: p.missing,
    checks: p.checks,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Telemetria por run (counters partilhados via Map keyed por runId)
// ─────────────────────────────────────────────────────────────────────────────
const TELEMETRY = new Map();

export function telemetryFor(runId) {
  let t = TELEMETRY.get(runId);
  if (!t) {
    t = {
      requests: 0,
      requestsViaTor: 0,
      newnyms: 0,
      exitIps: new Set(),
      leaksDetected: 0,
      proxyKindCounts: { direct: 0, http: 0, socks: 0 },
      startedAt: Date.now(),
    };
    TELEMETRY.set(runId, t);
  }
  return t;
}

export function snapshotTelemetry(runId) {
  const t = TELEMETRY.get(runId);
  if (!t) return null;
  return {
    requests: t.requests,
    requestsViaTor: t.requestsViaTor,
    newnyms: t.newnyms,
    exitIps: [...t.exitIps],
    leaksDetected: t.leaksDetected,
    proxyKindCounts: { ...t.proxyKindCounts },
    durationMs: Date.now() - t.startedAt,
    torRatio: t.requests > 0 ? t.requestsViaTor / t.requests : null,
  };
}

export function clearTelemetry(runId) {
  TELEMETRY.delete(runId);
}
