const EXTERNAL_TOOL_PACKS = [
  {
    id: 'dorks_lite',
    name: 'Dorks Lite',
    pipelineStage: 'discovery',
    category: 'discovery',
    intrusive: false,
    entrypoint: 'discovery/dorks-lite/dorks-lite.py',
    language: 'python',
    outputs: ['intel', 'artifact'],
  },
  {
    id: 'dorkforge_br',
    name: 'DorkForge BR',
    pipelineStage: 'discovery',
    category: 'discovery',
    intrusive: false,
    entrypoint: 'discovery/dorkforge-br/dorkforge.py',
    language: 'python',
    outputs: ['intel', 'artifact'],
  },
  {
    id: 'osint_suite',
    name: 'OSINT Suite',
    pipelineStage: 'discovery',
    category: 'discovery',
    intrusive: false,
    entrypoint: 'discovery/osint-suite/main.py',
    language: 'python',
    outputs: ['intel', 'artifact'],
  },
  {
    id: 'osintool',
    name: 'OSINTool',
    pipelineStage: 'discovery',
    category: 'discovery',
    intrusive: false,
    entrypoint: 'discovery/osintool/osintool.sh',
    language: 'bash',
    outputs: ['intel', 'artifact'],
  },
  {
    id: 'ssl_audit_kit',
    name: 'SSL Audit Kit',
    pipelineStage: 'surface',
    category: 'surface',
    intrusive: false,
    entrypoint: 'surface/ssl-audit-kit/ssl-audit-kit.py',
    language: 'python',
    outputs: ['finding', 'artifact'],
  },
  {
    id: 'wordpress_hunter',
    name: 'WordPress Hunter',
    pipelineStage: 'surface',
    category: 'surface',
    intrusive: false,
    entrypoint: 'surface/wordpress-hunter/wphunter.py',
    language: 'python',
    outputs: ['finding', 'artifact'],
  },
  {
    id: 'idor_scanner',
    name: 'IDOR Scanner',
    pipelineStage: 'validation',
    category: 'validation',
    intrusive: true,
    entrypoint: 'validation/idor-scanner/idor_scanner.py',
    language: 'python',
    outputs: ['finding', 'artifact'],
  },
  {
    id: 'port_scanner',
    name: 'Port Scanner',
    pipelineStage: 'aggressive',
    category: 'aggressive',
    intrusive: true,
    entrypoint: 'aggressive/port-scanner/port-scanner.py',
    language: 'python',
    outputs: ['finding', 'artifact'],
  },
  {
    id: 'autopentest',
    name: 'AutoPentest',
    pipelineStage: 'aggressive',
    category: 'aggressive',
    intrusive: true,
    entrypoint: 'aggressive/autopentest/autopentest.py',
    language: 'python',
    outputs: ['finding', 'artifact'],
  },
  {
    id: 'bug_bounty_kit',
    name: 'BugBountyKit',
    pipelineStage: 'aggressive',
    category: 'aggressive',
    intrusive: true,
    entrypoint: 'aggressive/bug-bounty-kit/bug-bounty-kit.sh',
    language: 'bash',
    outputs: ['finding', 'artifact'],
  },
  {
    id: 'cyberguard',
    name: 'Cyberguard',
    pipelineStage: 'aggressive',
    category: 'aggressive',
    intrusive: true,
    entrypoint: 'aggressive/cyberguard/cyberguard.py',
    language: 'python',
    outputs: ['finding', 'artifact'],
  },
  {
    id: 'metasploit_autorecon',
    name: 'MetaAutoRecon',
    pipelineStage: 'aggressive',
    category: 'aggressive',
    intrusive: true,
    entrypoint: 'aggressive/metasploit-autorecon/metasploit-autorecon.sh',
    language: 'bash',
    outputs: ['finding', 'artifact'],
  },
  {
    id: 'jarvis_security_framework',
    name: 'JARVIS Security Framework',
    pipelineStage: 'aggressive',
    category: 'aggressive',
    intrusive: true,
    entrypoint: 'aggressive/jarvis-security-framework/jarvis-security-framework.py',
    language: 'python',
    outputs: ['finding', 'artifact'],
  },
  {
    id: 'ctfmind',
    name: 'CTFMind',
    pipelineStage: 'standalone',
    category: 'ai',
    intrusive: false,
    entrypoint: 'standalone/ctfmind/ctfmind.sh',
    language: 'bash',
    outputs: ['artifact'],
  },
  {
    id: 'crypto_toolkit',
    name: 'Crypto Toolkit',
    pipelineStage: 'standalone',
    category: 'utility',
    intrusive: false,
    entrypoint: 'standalone/crypto-toolkit/crypto-toolkit.py',
    language: 'python',
    outputs: ['artifact'],
  },
  {
    id: 'pyshield_antivirus',
    name: 'PyShield Antivirus',
    pipelineStage: 'standalone',
    category: 'defensive',
    intrusive: false,
    entrypoint: 'standalone/pyshield-antivirus/Clean.py',
    language: 'python',
    outputs: ['artifact'],
  },
  {
    id: 'wireless_scanner',
    name: 'Wireless Scanner',
    pipelineStage: 'standalone',
    category: 'wireless',
    intrusive: true,
    entrypoint: 'standalone/wireless-scanner/wireless-scanner.py',
    language: 'python',
    outputs: ['finding', 'artifact'],
  },
  {
    id: 'news_verifier',
    name: 'News Verifier',
    pipelineStage: 'standalone',
    category: 'intel',
    intrusive: false,
    entrypoint: 'standalone/news-verifier/index.html',
    language: 'html',
    outputs: ['artifact'],
  },
];

export function listExternalToolPacks() {
  return EXTERNAL_TOOL_PACKS.map((pack) => ({ ...pack, outputs: [...pack.outputs] }));
}

export function getExternalToolPack(id) {
  const normalized = String(id || '').trim().toLowerCase().replace(/-/g, '_');
  return listExternalToolPacks().find((pack) => pack.id === normalized) || null;
}
