#!/usr/bin/env python3
"""
lovable-scan.py - fingerprint + RLS probe + secrets grep + misconfig (A05/A07/A02)
para apps Lovable.

Uso:
    python3 lovable-scan.py https://alvo.lovable.app
    python3 lovable-scan.py https://alvo.tld --tables users,profiles,orders
    python3 lovable-scan.py https://alvo.tld --no-probe        # sem RLS probe
    python3 lovable-scan.py https://alvo.tld --no-misconfig    # sem A05/A07/A02
    python3 lovable-scan.py https://alvo.tld --json out.json   # saida estruturada

Funciona com `requests` + `urllib` puro (fallback). Zero deps obrigatorias.

Modo seguro: so faz GET com `?limit=1`. NAO escreve no banco. Para PoC de
INSERT/UPDATE/DELETE, ver playbooks/lovable-checklist.md (manual).

Uso responsavel: somente em alvos com autorizacao explicita.
"""

from __future__ import annotations

import argparse
import base64
import json
import re
import sys
from urllib.parse import urljoin, urlparse

try:
    import requests  # type: ignore
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False
    from urllib.request import Request, urlopen
    from urllib.error import HTTPError, URLError


# ---------- patterns ----------

COMMON_TABLES = [
    "users", "profiles", "orders", "payments", "tickets", "messages",
    "posts", "comments", "subscriptions", "api_keys", "tokens",
    "sessions", "invoices", "leads", "accounts", "customers",
]

SECRET_PATTERNS = [
    ("stripe_secret",  re.compile(r"\bsk_(?:live|test)_[A-Za-z0-9]{20,}\b"), "critical"),
    ("supabase_jwt",   re.compile(r"\beyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\b"), "high"),
    ("resend_key",     re.compile(r"\bre_[A-Za-z0-9]{20,}\b"), "high"),
    ("openai_key",     re.compile(r"\bsk-[A-Za-z0-9_-]{32,}\b"), "high"),
    ("google_api_key", re.compile(r"\bAIza[0-9A-Za-z_-]{30,}\b"), "high"),
    ("github_pat",     re.compile(r"\bghp_[A-Za-z0-9]{36}\b"), "high"),
    ("gitlab_pat",     re.compile(r"\bglpat-[A-Za-z0-9_-]{20,}\b"), "high"),
    ("slack_bot",      re.compile(r"\bxoxb-[A-Za-z0-9-]{20,}\b"), "high"),
]

SUPABASE_URL_RE = re.compile(r"https?://([a-z0-9]{8,30})\.supabase\.co", re.I)
JS_BUNDLE_RE    = re.compile(r"""(?:src|href)\s*=\s*["']([^"']+\.(?:js|mjs))(?:\?[^"']*)?["']""", re.I)
LOVABLE_HINTS   = [
    re.compile(r"""<meta\s+name=["']lovable["']""", re.I),
    re.compile(r"lovable\.(app|dev|tagger|cdn)", re.I),
    re.compile(r"__LOVABLE__"),
    re.compile(r"data-lovable[-=]", re.I),
]

# A05/A06 - dotfiles e config files (path, severity, label)
COMMON_DOTFILES = [
    ("/.env", "critical", "dotenv"),
    ("/.env.production", "critical", "dotenv-prod"),
    ("/.env.local", "critical", "dotenv-local"),
    ("/.env.development", "high", "dotenv-dev"),
    ("/.git/config", "high", "git-config"),
    ("/.git/HEAD", "high", "git-head"),
    ("/package.json", "medium", "package-json"),
    ("/package-lock.json", "low", "package-lock"),
    ("/yarn.lock", "low", "yarn-lock"),
    ("/pnpm-lock.yaml", "low", "pnpm-lock"),
    ("/composer.json", "medium", "composer-json"),
    ("/composer.lock", "low", "composer-lock"),
    ("/.DS_Store", "low", "ds-store"),
]

# A07 - rotas que costumam responder 200 sem auth quando o LLM esquece middleware
COMMON_AUTHLESS_ENDPOINTS = [
    "/api/admin", "/api/admin/users", "/api/users", "/api/users/list",
    "/api/me", "/api/private", "/api/internal", "/api/debug",
    "/api/stats", "/api/export", "/api/account", "/api/config",
    "/api/health/secrets",
]

# A02/A05 - headers obrigatorios
REQUIRED_SECURITY_HEADERS = [
    "content-security-policy",
    "strict-transport-security",
    "x-frame-options",
    "x-content-type-options",
    "referrer-policy",
]

# Validadores de conteudo p/ evitar falso positivo de SPA fallback
DOTFILE_VALIDATORS = {
    "package-json":  re.compile(r'"dependencies"|"name"\s*:'),
    "composer-json": re.compile(r'"require"\s*:'),
    "git-config":    re.compile(r"\[core\]", re.I),
    "git-head":      re.compile(r"^ref:\s*refs/", re.I | re.M),
    "package-lock":  re.compile(r'"lockfileVersion"'),
    "yarn-lock":     re.compile(r"^# THIS IS AN AUTOGENERATED FILE", re.M),
    "pnpm-lock":     re.compile(r"^lockfileVersion:", re.M),
    "composer-lock": re.compile(r'"_readme"|"packages"'),
}
DOTENV_KEY_RE = re.compile(r"^([A-Z][A-Z0-9_]+)\s*=", re.M)
HTML_RE = re.compile(r"<html[\s>]|<!doctype html", re.I)


# ---------- ANSI colors ----------

class C:
    BOLD = "\033[1m"; RESET = "\033[0m"
    R = "\033[31m"; G = "\033[32m"; Y = "\033[33m"; B = "\033[34m"; M = "\033[35m"; CY = "\033[36m"


def banner():
    print(f"{C.M}{C.BOLD}", end="")
    print(r"""
   _                 _     _
  | |   _____ ____ _| |__ | | ___ ______ ___  ___ __ _ _ __
  | |  / _ \ \ / / _` | '_ \| |/ _ \______/ __|/ __/ _` | '_ \
  | |_| (_) \ V / (_| | |_) | |  __/      \__ \ (_| (_| | | | |
  |_____\___/ \_/\__,_|_.__/|_|\___|      |___/\___\__,_|_| |_|
""")
    print(f"{C.RESET}{C.CY}  GHOSTRECON | Lovable hunt | RLS / secrets / misconfig{C.RESET}\n")


# ---------- HTTP helpers ----------

def http_get_full(url, headers=None, timeout=12):
    headers = headers or {}
    headers.setdefault("User-Agent", "GHOSTRECON-lovable-scan/1.0")
    if HAS_REQUESTS:
        try:
            r = requests.get(url, headers=headers, timeout=timeout, allow_redirects=True)
            hdrs = {k.lower(): v for k, v in r.headers.items()}
            return r.status_code, r.text, hdrs
        except requests.RequestException:
            return 0, "", {}
    else:
        try:
            req = Request(url, headers=headers)
            with urlopen(req, timeout=timeout) as resp:
                body = resp.read().decode("utf-8", errors="replace")
                hdrs = {k.lower(): v for k, v in dict(resp.getheaders()).items()}
                return resp.status, body, hdrs
        except HTTPError as e:
            try:
                hdrs = {k.lower(): v for k, v in dict(e.headers or {}).items()}
            except Exception:
                hdrs = {}
            return e.code, "", hdrs
        except (URLError, Exception):
            return 0, "", {}


def http_get(url, headers=None, timeout=12):
    code, body, _ = http_get_full(url, headers, timeout)
    return code, body


def http_get_json(url, headers=None, timeout=12):
    code, body = http_get(url, headers, timeout)
    if code != 200 or not body:
        return code, None
    try:
        return code, json.loads(body)
    except json.JSONDecodeError:
        return code, None


# ---------- helpers ----------

def decode_jwt_claims(jwt):
    try:
        parts = jwt.split(".")
        if len(parts) != 3:
            return None
        b64 = parts[1].replace("-", "+").replace("_", "/")
        b64 += "=" * (-len(b64) % 4)
        return json.loads(base64.b64decode(b64).decode("utf-8", errors="replace"))
    except Exception:
        return None


def is_lovable_host(url):
    try:
        host = urlparse(url).hostname or ""
        return host.endswith(".lovable.app") or host.endswith(".lovable.dev")
    except Exception:
        return False


def is_lovable_markup(html):
    return any(p.search(html) for p in LOVABLE_HINTS)


def extract_unique(text, regex):
    seen, out = set(), []
    for m in regex.finditer(text):
        v = m.group(1) if m.groups() else m.group(0)
        if v not in seen:
            seen.add(v)
            out.append(v)
    return out


def mask(secret, keep=12):
    return f"{secret[:keep]}...({len(secret)}c)" if len(secret) > keep else secret


# ---------- new probes (A05/A07/A02) ----------

def probe_dotfiles(target):
    """A05/A06 - testa dotfiles e lockfiles expostos."""
    out = []
    for path, sev, label in COMMON_DOTFILES:
        url = urljoin(target, path)
        code, body, hdrs = http_get_full(url)
        if code != 200 or not body:
            continue
        if HTML_RE.search(body):
            continue
        valid = False
        ct = hdrs.get("content-type", "").lower()

        validator = DOTFILE_VALIDATORS.get(label)
        if validator and validator.search(body):
            valid = True
        elif label.startswith("dotenv") and DOTENV_KEY_RE.search(body):
            valid = True
        elif label == "ds-store" and len(body) > 16:
            valid = True
        elif "json" in ct and body.lstrip().startswith("{"):
            valid = True

        if not valid:
            continue

        extra = {}
        if label == "package-json":
            try:
                pkg = json.loads(body)
                deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
                extra["deps"] = [f"{n}@{v}" for n, v in list(deps.items())[:80]]
                extra["dep_count"] = len(deps)
            except Exception:
                pass
        if label.startswith("dotenv"):
            extra["env_key_names"] = [m.group(1) for m in DOTENV_KEY_RE.finditer(body)][:30]

        out.append({
            "path": path, "label": label, "severity": sev,
            "url": url, "size": len(body), "content_type": ct, **extra,
        })
    return out


def probe_sourcemaps(target, bundle_paths):
    """A05 - source maps deixados em producao."""
    out = []
    for js in bundle_paths[:6]:
        try:
            map_url = urljoin(target, js) + ".map"
        except Exception:
            continue
        code, body = http_get(map_url)
        if code != 200 or not body:
            continue
        if not (re.search(r'"version"\s*:\s*\d', body) and re.search(r'"sources"\s*:', body)):
            continue
        try:
            j = json.loads(body)
            srcs = len(j.get("sources", [])) if isinstance(j, dict) else 0
        except Exception:
            srcs = 0
        out.append({"url": map_url, "source_count": srcs, "size": len(body)})
    return out


def probe_cors(target):
    """A05 - CORS reflete Origin atacante?"""
    attacker = "https://attacker-cors-test.invalid"
    code, _body, hdrs = http_get_full(target, {"Origin": attacker})
    if code == 0:
        return None
    aco = hdrs.get("access-control-allow-origin", "")
    acc = hdrs.get("access-control-allow-credentials", "")
    if not aco:
        return None
    reflects = aco == attacker or aco == "*"
    if not reflects:
        return None
    return {
        "acao": aco,
        "acac": acc,
        "critical_combo": (aco == attacker and acc.lower() == "true"),
    }


def probe_authless_endpoints(target):
    """A07 - rotas comuns que respondem 200 sem Authorization."""
    out = []
    for path in COMMON_AUTHLESS_ENDPOINTS:
        url = urljoin(target, path)
        code, body, hdrs = http_get_full(url)
        if code != 200 or not body:
            continue
        if HTML_RE.search(body):
            continue
        ct = hdrs.get("content-type", "").lower()
        looks_jsonish = "json" in ct or body.lstrip().startswith(("{", "["))
        if not looks_jsonish:
            continue
        out.append({"path": path, "url": url, "size": len(body), "content_type": ct})
    return out


def probe_security_headers(root_headers):
    """A02/A05 - headers de seguranca ausentes."""
    return [h for h in REQUIRED_SECURITY_HEADERS if h not in (root_headers or {})]


# ---------- core ----------

def scan_target(target, tables, probe_rls, probe_misconfig, max_bundles):
    findings = []
    ctx = {
        "target": target,
        "is_lovable": False,
        "supabase_url": None,
        "anon_key": None,
        "anon_key_claims": None,
        "service_role_jwt": None,
        "secrets_found": [],
        "bundles_scanned": 0,
        "rls_broken_tables": [],
        "dotfiles_exposed": [],
        "sourcemaps_exposed": [],
        "cors_permissive": None,
        "authless_endpoints": [],
        "missing_security_headers": [],
    }

    # 1) HTML root + headers
    print(f"{C.B}[*]{C.RESET} GET {target}")
    code, html, root_headers = http_get_full(target)
    if code == 0:
        print(f"{C.R}[!]{C.RESET} Falha ao buscar root.")
        return {"context": ctx, "findings": findings}
    print(f"    -> {code} | {len(html)} bytes")

    # 2) Lovable fingerprint
    by_host = is_lovable_host(target)
    by_html = is_lovable_markup(html)
    ctx["is_lovable"] = by_host or by_html
    if ctx["is_lovable"]:
        print(f"{C.G}[+]{C.RESET} Lovable detectado ({'hostname' if by_host else 'markup'})")
        findings.append({"type": "tech_fingerprint", "value": "Lovable platform",
                         "severity": "info", "evidence": "hostname" if by_host else "markup"})
    else:
        print(f"{C.Y}[-]{C.RESET} Sem assinatura Lovable. Continuando (Supabase e o pivot).")

    # 3) URLs Supabase + bundles JS
    sb_urls = {f"https://{s}.supabase.co" for s in extract_unique(html, SUPABASE_URL_RE)}
    bundles = extract_unique(html, JS_BUNDLE_RE)[:max_bundles]
    print(f"{C.B}[*]{C.RESET} {len(bundles)} bundle(s) JS para inspecionar")

    blob = [html]
    for rel in bundles:
        try:
            abs_url = urljoin(target, rel)
        except Exception:
            continue
        c, body = http_get(abs_url)
        if c == 200 and body:
            ctx["bundles_scanned"] += 1
            blob.append(body)
            for sb_match in extract_unique(body, SUPABASE_URL_RE):
                sb_urls.add(f"https://{sb_match}.supabase.co")
            print(f"    -> {C.G}{c}{C.RESET} {abs_url} ({len(body)}b)")
        else:
            print(f"    -> {C.Y}{c}{C.RESET} {abs_url}")

    sb_url = next(iter(sb_urls), None)
    ctx["supabase_url"] = sb_url
    if sb_url:
        print(f"{C.G}[+]{C.RESET} Supabase endpoint: {C.BOLD}{sb_url}{C.RESET}")
        findings.append({"type": "supabase_endpoint", "value": sb_url, "severity": "info"})
    else:
        print(f"{C.Y}[-]{C.RESET} Nenhuma URL Supabase encontrada no bundle.")

    # 4) Secrets grep
    seen = set()
    for chunk in blob:
        for name, regex, sev in SECRET_PATTERNS:
            for sec in extract_unique(chunk, regex):
                key = (name, sec)
                if key in seen:
                    continue
                seen.add(key)

                claims = None
                role_note = ""
                if name == "supabase_jwt":
                    claims = decode_jwt_claims(sec)
                    if claims:
                        role_note = f" role={claims.get('role')} ref={claims.get('ref')}"
                        if claims.get("role") == "anon":
                            ctx["anon_key"] = sec
                            ctx["anon_key_claims"] = claims
                        elif claims.get("role") == "service_role":
                            ctx["service_role_jwt"] = sec
                            sev = "critical"

                color = C.R if sev == "critical" else C.Y
                print(f"{color}[!]{C.RESET} {sev.upper():<8} {name:<18} {mask(sec)}{role_note}")
                ftype = ("supabase_anon_key_embedded"
                         if (name == "supabase_jwt" and claims and claims.get("role") == "anon")
                         else "secret_exposed_client")
                findings.append({
                    "type": ftype,
                    "value": f"{name}: {mask(sec)}",
                    "severity": sev,
                    "pattern": name,
                    "claims": claims,
                })
                ctx["secrets_found"].append({"pattern": name, "masked": mask(sec), "claims": claims})

    if ctx.get("service_role_jwt"):
        print(f"{C.R}{C.BOLD}[!] CRITICO:{C.RESET}{C.R} service_role JWT no bundle - bypass total de RLS!{C.RESET}")

    # 5) RLS probe
    if probe_rls and sb_url and ctx.get("anon_key"):
        print(f"\n{C.B}[*]{C.RESET} Probe RLS (somente leitura, limit=1) em {len(tables)} tabelas...")
        anon = ctx["anon_key"]
        headers = {"apikey": anon, "Authorization": f"Bearer {anon}"}
        for t in tables:
            url = f"{sb_url}/rest/v1/{t}?select=*&limit=1"
            code_t, data = http_get_json(url, headers)
            if code_t == 200:
                rows = len(data) if isinstance(data, list) else 0
                cols = list(data[0].keys()) if (isinstance(data, list) and rows and isinstance(data[0], dict)) else []
                more = "..." if len(cols) > 6 else ""
                print(f"    {C.R}[!]{C.RESET} 200  {t:<20}  rows={rows}  cols={cols[:6]}{more}")
                findings.append({
                    "type": "supabase_rls_missing",
                    "value": f"Tabela {t} acessivel com anon key",
                    "severity": "critical",
                    "table": t,
                    "rowCount": rows,
                    "columns": cols,
                    "cve": "CVE-2025-48757",
                    "cvss": 8.26,
                    "url": url,
                })
                ctx["rls_broken_tables"].append({"table": t, "rowCount": rows, "columns": cols})
            elif code_t in (401, 403):
                print(f"    {C.G}[ok]{C.RESET} {code_t}  {t}")
            elif code_t == 404:
                pass
            else:
                print(f"    {C.Y}[?]{C.RESET}  {code_t}  {t}")
    elif probe_rls and sb_url and not ctx.get("anon_key"):
        print(f"{C.Y}[-]{C.RESET} Anon key nao extraida do bundle - probe de RLS pulado.")
    elif probe_rls and not sb_url:
        print(f"{C.Y}[-]{C.RESET} Sem URL Supabase - probe de RLS pulado.")

    # 6) Misconfiguration probes (A05/A07/A02)
    if probe_misconfig:
        print(f"\n{C.B}[*]{C.RESET} Misconfiguration probes (A05/A07/A02)...")

        # 6a) Dotfiles
        dot = probe_dotfiles(target)
        ctx["dotfiles_exposed"] = dot
        for f in dot:
            color = C.R if f["severity"] in ("critical", "high") else C.Y
            extras = ""
            if f["label"] == "package-json" and f.get("dep_count"):
                extras = f"  [{f['dep_count']} deps]"
            elif f["label"].startswith("dotenv") and f.get("env_key_names"):
                extras = f"  keys={f['env_key_names'][:5]}..."
            print(f"    {color}[!]{C.RESET} {f['severity'].upper():<8} {f['label']:<14} {f['path']}{extras}")
            f_pruned = {k: v for k, v in f.items() if k not in ("severity", "url", "path", "label")}
            findings.append({
                "type": "expose_dotfile",
                "value": f"{f['label']} acessivel em {f['path']}",
                "severity": f["severity"],
                "url": f["url"],
                "owasp": "A05:2021",
                **f_pruned,
            })
        if not dot:
            print(f"    {C.G}[ok]{C.RESET} nenhum dotfile/lockfile exposto")

        # 6b) Source maps
        if bundles:
            maps = probe_sourcemaps(target, bundles)
            ctx["sourcemaps_exposed"] = maps
            for sm in maps:
                print(f"    {C.Y}[!]{C.RESET} MEDIUM   sourcemap     {sm['url']}  ({sm['source_count']} sources)")
                findings.append({
                    "type": "expose_sourcemap",
                    "value": f"Source map em producao ({sm['source_count']} sources)",
                    "severity": "medium",
                    "url": sm["url"],
                    "source_count": sm["source_count"],
                    "owasp": "A05:2021",
                })
            if not maps:
                print(f"    {C.G}[ok]{C.RESET} nenhum source map exposto")

        # 6c) CORS
        cors = probe_cors(target)
        ctx["cors_permissive"] = cors
        if cors:
            sev = "high" if cors["critical_combo"] else "medium"
            color = C.R if sev == "high" else C.Y
            note = " + Allow-Credentials:true (CRITICO)" if cors["critical_combo"] else ""
            print(f"    {color}[!]{C.RESET} {sev.upper():<8} cors          ACAO={cors['acao']}{note}")
            findings.append({
                "type": "cors_permissive",
                "value": f"CORS reflete origin atacante; ACAO={cors['acao']}",
                "severity": sev,
                "url": target,
                "acao": cors["acao"],
                "acac": cors["acac"],
                "critical_combo": cors["critical_combo"],
                "owasp": "A05:2021",
            })
        else:
            print(f"    {C.G}[ok]{C.RESET} CORS nao reflete origin atacante")

        # 6d) Auth-less endpoints
        authless = probe_authless_endpoints(target)
        ctx["authless_endpoints"] = authless
        for a in authless:
            print(f"    {C.R}[!]{C.RESET} HIGH     api_no_auth   {a['path']}  ({a['size']}b {a['content_type']})")
            findings.append({
                "type": "api_no_auth",
                "value": f"{a['path']} responde 200 sem Authorization",
                "severity": "high",
                "url": a["url"],
                "path": a["path"],
                "owasp": "A07:2021",
            })
        if not authless:
            print(f"    {C.G}[ok]{C.RESET} nenhum endpoint /api/* aberto sem auth")

        # 6e) Security headers
        missing = probe_security_headers(root_headers)
        ctx["missing_security_headers"] = missing
        if len(missing) >= 3:
            critical_pair = any(h in missing for h in ("content-security-policy", "strict-transport-security"))
            sev = "medium" if critical_pair else "low"
            print(f"    {C.Y}[!]{C.RESET} {sev.upper():<8} sec_headers   ausentes={missing}")
            findings.append({
                "type": "security_headers_missing",
                "value": f"{len(missing)} headers de seguranca ausentes",
                "severity": sev,
                "url": target,
                "missing": missing,
                "owasp": "A05:2021",
            })
        elif missing:
            print(f"    {C.G}[ok]{C.RESET} headers OK ({len(missing)} ausentes - abaixo do limiar)")
        else:
            print(f"    {C.G}[ok]{C.RESET} todos os headers de seguranca presentes")

    # 7) Resumo
    print(f"\n{C.BOLD}-- Resumo --{C.RESET}")
    print(f"  Lovable                 : {ctx['is_lovable']}")
    print(f"  Supabase                : {ctx['supabase_url'] or '-'}")
    print(f"  Anon key embedded       : {'sim' if ctx['anon_key'] else 'nao'}")
    sr_label = (C.R + 'SIM (CRITICO)' + C.RESET) if ctx['service_role_jwt'] else 'nao'
    print(f"  service_role no bundle  : {sr_label}")
    print(f"  Secrets totais          : {len(ctx['secrets_found'])}")
    print(f"  Tabelas com RLS quebrada: {len(ctx['rls_broken_tables'])}")
    if ctx["rls_broken_tables"]:
        for b in ctx["rls_broken_tables"]:
            print(f"    - {b['table']}  ({b['rowCount']} row, {len(b['columns'])} cols)")
    print(f"  Dotfiles expostos       : {len(ctx['dotfiles_exposed'])}")
    if ctx["dotfiles_exposed"]:
        for d in ctx["dotfiles_exposed"]:
            print(f"    - [{d['severity']}] {d['path']}")
    print(f"  Source maps expostos    : {len(ctx['sourcemaps_exposed'])}")
    print(f"  CORS permissivo         : {'sim' if ctx['cors_permissive'] else 'nao'}")
    print(f"  Endpoints sem auth      : {len(ctx['authless_endpoints'])}")
    if ctx["authless_endpoints"]:
        for a in ctx["authless_endpoints"]:
            print(f"    - {a['path']}")
    print(f"  Headers ausentes        : {len(ctx['missing_security_headers'])}")

    return {"context": ctx, "findings": findings}


def main():
    parser = argparse.ArgumentParser(
        description="GHOSTRECON | Lovable hunt - fingerprint, secrets, RLS probe, misconfig (A05/A07/A02).",
    )
    parser.add_argument("target", help="URL alvo (ex.: https://alvo.lovable.app)")
    parser.add_argument("--tables", default=",".join(COMMON_TABLES),
                        help="Tabelas Supabase a probar (CSV)")
    parser.add_argument("--no-probe", action="store_true",
                        help="Pula probe RLS (apenas fingerprint + secrets)")
    parser.add_argument("--no-misconfig", action="store_true",
                        help="Pula probes A05/A07/A02 (dotfiles, source maps, CORS, auth-less, headers)")
    parser.add_argument("--max-bundles", type=int, default=8,
                        help="Quantos bundles JS analisar (default 8)")
    parser.add_argument("--json", metavar="FILE",
                        help="Grava resultado estruturado neste ficheiro")
    parser.add_argument("--no-banner", action="store_true")
    args = parser.parse_args()

    if not args.no_banner:
        banner()

    target = args.target.rstrip("/")
    if not target.startswith(("http://", "https://")):
        target = "https://" + target

    tables = [t.strip() for t in args.tables.split(",") if t.strip()]

    result = scan_target(
        target=target,
        tables=tables,
        probe_rls=not args.no_probe,
        probe_misconfig=not args.no_misconfig,
        max_bundles=args.max_bundles,
    )

    if args.json:
        with open(args.json, "w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False, indent=2)
        print(f"\n{C.G}[+]{C.RESET} JSON salvo em {args.json}")

    severities = {f.get("severity") for f in result["findings"]}
    if "critical" in severities:
        sys.exit(1)
    if "high" in severities:
        sys.exit(2)
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n[abortado]")
        sys.exit(130)
verity": "info"})
    else:
        print(f"{C.Y}[-]{C.RESET} Nenhuma URL Supabase encontrada no bundle.")

    # 4) Secrets grep
    seen = set()
    for chunk in blob:
        for name, regex, sev in SECRET_PATTERNS:
            for sec in extract_unique(chunk, regex):
                key = (name, sec)
                if key in seen:
                    continue
                seen.add(key)

                claims = None
                role_note = ""
                if name == "supabase_jwt":
                    claims = decode_jwt_claims(sec)
                    if claims:
                        role_note = f" role={claims.get('role')} ref={claims.get('ref')}"
                        if claims.get("role") == "anon":
                            ctx["anon_key"] = sec
                            ctx["anon_key_claims"] = claims
                        elif claims.get("role") == "service_role":
                            ctx["service_role_jwt"] = sec
                            sev = "critical"

                color = C.R if sev == "critical" else C.Y
                print(f"{color}[!]{C.RESET} {sev.upper():<8} {name:<18} {mask(sec)}{role_note}")
                ftype = ("supabase_anon_key_embedded"
                         if (name == "supabase_jwt" and claims and claims.get("role") == "anon")
                         else "secret_exposed_client")
                findings.append({
                    "type": ftype,
                    "value": f"{name}: {mask(sec)}",
                    "severity": sev,
                    "pattern": name,
                    "claims": claims,
                })
                ctx["secrets_found"].append({"pattern": name, "masked": mask(sec), "claims": claims})

    if ctx.get("service_role_jwt"):
        print(f"{C.R}{C.BOLD}[!] CRITICO:{C.RESET}{C.R} service_role JWT no bundle - bypass total de RLS!{C.RESET}")

    # 5) RLS probe
    if probe_rls and sb_url and ctx.get("anon_key"):
        print(f"\n{C.B}[*]{C.RESET} Probe RLS (somente leitura, limit=1) em {len(tables)} tabelas...")
        anon = ctx["anon_key"]
        headers = {"apikey": anon, "Authorization": f"Bearer {anon}"}
        for t in tables:
            url = f"{sb_url}/rest/v1/{t}?select=*&limit=1"
            code_t, data = http_get_json(url, headers)
            if code_t == 200:
                rows = len(data) if isinstance(data, list) else 0
                cols = list(data[0].keys()) if (isinstance(data, list) and rows and isinstance(data[0], dict)) else []
                more = "..." if len(cols) > 6 else ""
                print(f"    {C.R}[!]{C.RESET} 200  {t:<20}  rows={rows}  cols={cols[:6]}{more}")
                findings.append({
                    "type": "supabase_rls_missing",
                    "value": f"Tabela {t} acessivel com anon key",
                    "severity": "critical",
                    "table": t,
                    "rowCount": rows,
                    "columns": cols,
                    "cve": "CVE-2025-48757",
                    "cvss": 8.26,
                    "url": url,
                })
                ctx["rls_broken_tables"].append({"table": t, "rowCount": rows, "columns": cols})
            elif code_t in (401, 403):
                print(f"    {C.G}[ok]{C.RESET} {code_t}  {t}")
            elif code_t == 404:
                pass
            else:
                print(f"    {C.Y}[?]{C.RESET}  {code_t}  {t}")
    elif probe_rls and sb_url and not ctx.get("anon_key"):
        print(f"{C.Y}[-]{C.RESET} Anon key nao extraida do bundle - probe de RLS pulado.")
    elif probe_rls and not sb_url:
        print(f"{C.Y}[-]{C.RESET} Sem URL Supabase - probe de RLS pulado.")

    # 6) Misconfiguration probes (A05/A07/A02)
    if probe_misconfig:
        print(f"\n{C.B}[*]{C.RESET} Misconfiguration probes (A05/A07/A02)...")

        # 6a) Dotfiles
        dot = probe_dotfiles(target)
        ctx["dotfiles_exposed"] = dot
        for f in dot:
            color = C.R if f["severity"] in ("critical", "high") else C.Y
            extras = ""
            if f["label"] == "package-json" and f.get("dep_count"):
                extras = f"  [{f['dep_count']} deps]"
            elif f["label"].startswith("dotenv") and f.get("env_key_names"):
                extras = f"  keys={f['env_key_names'][:5]}..."
            print(f"    {color}[!]{C.RESET} {f['severity'].upper():<8} {f['label']:<14} {f['path']}{extras}")
            f_pruned = {k: v for k, v in f.items() if k not in ("severity", "url", "path", "label")}
            findings.append({
                "type": "expose_dotfile",
                "value": f"{f['label']} acessivel em {f['path']}",
                "severity": f["severity"],
                "url": f["url"],
                "owasp": "A05:2021",
                **f_pruned,
            })
        if not dot:
            print(f"    {C.G}[ok]{C.RESET} nenhum dotfile/lockfile exposto")

        # 6b) Source maps
        if bundles:
            maps = probe_sourcemaps(target, bundles)
            ctx["sourcemaps_exposed"] = maps
            for sm in maps:
                print(f"    {C.Y}[!]{C.RESET} MEDIUM   sourcemap     {sm['url']}  ({sm['source_count']} sources)")
                findings.append({
                    "type": "expose_sourcemap",
                    "value": f"Source map em producao ({sm['source_count']} sources)",
                    "severity": "medium",
                    "url": sm["url"],
                    "source_count": sm["source_count"],
                    "owasp": "A05:2021",
                })
            if not maps:
                print(f"    {C.G}[ok]{C.RESET} nenhum source map exposto")

        # 6c) CORS
        cors = probe_cors(target)
        ctx["cors_permissive"] = cors
        if cors:
            sev = "high" if cors["critical_combo"] else "medium"
            color = C.R if sev == "high" else C.Y
            note = " + Allow-Credentials:true (CRITICO)" if cors["critical_combo"] else ""
            print(f"    {color}[!]{C.RESET} {sev.upper():<8} cors          ACAO={cors['acao']}{note}")
            findings.append({
                "type": "cors_permissive",
                "value": f"CORS reflete origin atacante; ACAO={cors['acao']}",
                "severity": sev,
                "url": target,
                "acao": cors["acao"],
                "acac": cors["acac"],
                "critical_combo": cors["critical_combo"],
                "owasp": "A05:2021",
            })
        else:
            print(f"    {C.G}[ok]{C.RESET} CORS nao reflete origin atacante")

        # 6d) Auth-less endpoints
        authless = probe_authless_endpoints(target)
        ctx["authless_endpoints"] = authless
        for a in authless:
            print(f"    {C.R}[!]{C.RESET} HIGH     api_no_auth   {a['path']}  ({a['size']}b {a['content_type']})")
            findings.append({
                "type": "api_no_auth",
                "value": f"{a['path']} responde 200 sem Authorization",
                "severity": "high",
                "url": a["url"],
                "path": a["path"],
                "owasp": "A07:2021",
            })
        if not authless:
            print(f"    {C.G}[ok]{C.RESET} nenhum endpoint /api/* aberto sem auth")

        # 6e) Security headers
        missing = probe_security_headers(root_headers)
        ctx["missing_security_headers"] = missing
        if len(missing) >= 3:
            critical_pair = any(h in missing for h in ("content-security-policy", "strict-transport-security"))
            sev = "medium" if critical_pair else "low"
            print(f"    {C.Y}[!]{C.RESET} {sev.upper():<8} sec_headers   ausentes={missing}")
            findings.append({
                "type": "security_headers_missing",
                "value": f"{len(missing)} headers de seguranca ausentes",
                "severity": sev,
                "url": target,
                "missing": missing,
                "owasp": "A05:2021",
            })
        elif missing:
            print(f"    {C.G}[ok]{C.RESET} headers OK ({len(missing)} ausentes - abaixo do limiar)")
        else:
            print(f"    {C.G}[ok]{C.RESET} todos os headers de seguranca presentes")

    # 7) Resumo
    print(f"\n{C.BOLD}-- Resumo --{C.RESET}")
    print(f"  Lovable                 : {ctx['is_lovable']}")
    print(f"  Supabase                : {ctx['supabase_url'] or '-'}")
    print(f"  Anon key embedded       : {'sim' if ctx['anon_key'] else 'nao'}")
    sr_label = (C.R + 'SIM (CRITICO)' + C.RESET) if ctx['service_role_jwt'] else 'nao'
    print(f"  service_role no bundle  : {sr_label}")
    print(f"  Secrets totais          : {len(ctx['secrets_found'])}")
    print(f"  Tabelas com RLS quebrada: {len(ctx['rls_broken_tables'])}")
    if ctx["rls_broken_tables"]:
        for b in ctx["rls_broken_tables"]:
            print(f"    - {b['table']}  ({b['rowCount']} row, {len(b['columns'])} cols)")
    print(f"  Dotfiles expostos       : {len(ctx['dotfiles_exposed'])}")
    if ctx["dotfiles_exposed"]:
        for d in ctx["dotfiles_exposed"]:
            print(f"    - [{d['severity']}] {d['path']}")
    print(f"  Source maps expostos    : {len(ctx['sourcemaps_exposed'])}")
    print(f"  CORS permissivo         : {'sim' if ctx['cors_permissive'] else 'nao'}")
    print(f"  Endpoints sem auth      : {len(ctx['authless_endpoints'])}")
    if ctx["authless_endpoints"]:
        for a in ctx["authless_endpoints"]:
            print(f"    - {a['path']}")
    print(f"  Headers ausentes        : {len(ctx['missing_security_headers'])}")

    return {"context": ctx, "findings": findings}


def main():
    parser = argparse.ArgumentParser(
        description="GHOSTRECON | Lovable hunt - fingerprint, secrets, RLS probe, misconfig (A05/A07/A02).",
    )
    parser.add_argument("target", help="URL alvo (ex.: https://alvo.lovable.app)")
    parser.add_argument("--tables", default=",".join(COMMON_TABLES),
                        help="Tabelas Supabase a probar (CSV)")
    parser.add_argument("--no-probe", action="store_true",
                        help="Pula probe RLS (apenas fingerprint + secrets)")
    parser.add_argument("--no-misconfig", action="store_true",
                        help="Pula probes A05/A07/A02 (dotfiles, source maps, CORS, auth-less, headers)")
    parser.add_argument("--max-bundles", type=int, default=8,
                        help="Quantos bundles JS analisar (default 8)")
    parser.add_argument("--json", metavar="FILE",
                        help="Grava resultado estruturado neste ficheiro")
    parser.add_argument("--no-banner", action="store_true")
    args = parser.parse_args()

    if not args.no_banner:
        banner()

    target = args.target.rstrip("/")
    if not target.startswith(("http://", "https://")):
        target = "https://" + target

    tables = [t.strip() for t in args.tables.split(",") if t.strip()]

    result = scan_target(
        target=target,
        tables=tables,
        probe_rls=not args.no_probe,
        probe_misconfig=not args.no_misconfig,
        max_bundles=args.max_bundles,
    )

    if args.json:
        with open(args.json, "w", encoding="utf-8") as f:
            json.dump(result, f, ensure_ascii=False, indent=2)
        print(f"\n{C.G}[+]{C.RESET} JSON salvo em {args.json}")

    severities = {f.get("severity") for f in result["findings"]}
    if "critical" in severities:
        sys.exit(1)
    if "high" in severities:
        sys.exit(2)
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n[abortado]")
        sys.exit(130)
